'use client'
import Menu from './components/navigation/menu'
import Navbar from './components/navigation/navbar'
import './globals.css'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* className={inter.className} */}
      <body className='h-screen flex flex-col'>
        <Navbar />
      <div className='flex'>
        <div className='menu- mt-16 w-1/5'>
          <Menu />
        </div>
        <div className='blog- mt-20 w-4/5 m-4'>
          {children}
        </div>
      </div>
     
        
      </body>
    </html>
  )
}
